version: "3.8"

networks:
  services:
    name: mongodb.network

services:
  mongodb:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_USER_PASSWORD: ${MONGO_USER_USERNAME}
      MONGO_USER_PASSWORD: ${MONGO_USER_PASSWORD}
      MONGO_DATABASE_NAME: ${MONGO_DATABASE_NAME}
    networks:
      - services
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    networks:
      - services
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_USER_PASSWORD}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${MONGO_DATABASE_NAME}
